"""empty message

Revision ID: 25182b8be3c9
Revises: 
Create Date: 2020-06-27 15:53:54.759215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25182b8be3c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_data',
    sa.Column('BASE_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Base_Text', sa.Text(), nullable=False),
    sa.Column('Base_Text2', sa.String(length=20), nullable=True),
    sa.Column('Base_Num', sa.Integer(), nullable=True),
    sa.Column('InertDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('BASE_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_data')
    # ### end Alembic commands ###
